package info.meuse24.pdf_scanner.ui.theme

import androidx.compose.ui.graphics.Color

// Brand identity used as the seed family for the static Material 3 fallback.
val BrandDeepIndigo = Color(0xFF1C0078)
val BrandTeal = Color(0xFF00A992)
val BrandAmber = Color(0xFF8F4F00)

// Fallback light scheme for devices without dynamic color.
val LightPrimary = Color(0xFF4F43A9)
val LightOnPrimary = Color(0xFFFFFFFF)
val LightPrimaryContainer = Color(0xFFE6DEFF)
val LightOnPrimaryContainer = Color(0xFF170065)
val LightSecondary = Color(0xFF006B5D)
val LightOnSecondary = Color(0xFFFFFFFF)
val LightSecondaryContainer = Color(0xFF80F8E4)
val LightOnSecondaryContainer = Color(0xFF00201B)
val LightTertiary = Color(0xFF8C5000)
val LightOnTertiary = Color(0xFFFFFFFF)
val LightTertiaryContainer = Color(0xFFFFDCC2)
val LightOnTertiaryContainer = Color(0xFF2D1600)
val LightError = Color(0xFFBA1A1A)
val LightOnError = Color(0xFFFFFFFF)
val LightErrorContainer = Color(0xFFFFDAD6)
val LightOnErrorContainer = Color(0xFF410002)
val LightBackground = Color(0xFFFFFBFF)
val LightOnBackground = Color(0xFF1C1B20)
val LightSurface = Color(0xFFFFFBFF)
val LightOnSurface = Color(0xFF1C1B20)
val LightSurfaceVariant = Color(0xFFE6E0EC)
val LightOnSurfaceVariant = Color(0xFF48454F)
val LightOutline = Color(0xFF79747E)
val LightOutlineVariant = Color(0xFFCAC4D0)
val LightInverseSurface = Color(0xFF313035)
val LightInverseOnSurface = Color(0xFFF4EFF7)
val LightInversePrimary = Color(0xFFC8BFFF)
val LightSurfaceTint = LightPrimary

// Fallback dark scheme for devices without dynamic color.
val DarkPrimary = Color(0xFFC8BFFF)
val DarkOnPrimary = Color(0xFF2A1978)
val DarkPrimaryContainer = Color(0xFF382A90)
val DarkOnPrimaryContainer = Color(0xFFE6DEFF)
val DarkSecondary = Color(0xFF61DBC8)
val DarkOnSecondary = Color(0xFF00382F)
val DarkSecondaryContainer = Color(0xFF005046)
val DarkOnSecondaryContainer = Color(0xFF80F8E4)
val DarkTertiary = Color(0xFFFFB86F)
val DarkOnTertiary = Color(0xFF4B2800)
val DarkTertiaryContainer = Color(0xFF6A3A00)
val DarkOnTertiaryContainer = Color(0xFFFFDCC2)
val DarkError = Color(0xFFFFB4AB)
val DarkOnError = Color(0xFF690005)
val DarkErrorContainer = Color(0xFF93000A)
val DarkOnErrorContainer = Color(0xFFFFDAD6)
val DarkBackground = Color(0xFF141318)
val DarkOnBackground = Color(0xFFE6E1E9)
val DarkSurface = Color(0xFF141318)
val DarkOnSurface = Color(0xFFE6E1E9)
val DarkSurfaceVariant = Color(0xFF48454F)
val DarkOnSurfaceVariant = Color(0xFFCAC4D0)
val DarkOutline = Color(0xFF948F99)
val DarkOutlineVariant = Color(0xFF48454F)
val DarkInverseSurface = Color(0xFFE6E1E9)
val DarkInverseOnSurface = Color(0xFF313035)
val DarkInversePrimary = Color(0xFF4F43A9)
val DarkSurfaceTint = DarkPrimary
