Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

$repoRoot = Split-Path -Parent $PSScriptRoot
$appSources = Join-Path $repoRoot "app\src\main\java"
$filledOutput = Join-Path $repoRoot "app\src\main\java\androidx\compose\material\icons\filled\ProjectMaterialIcons.kt"
$autoMirroredOutput = Join-Path $repoRoot "app\src\main\java\androidx\compose\material\icons\automirrored\filled\ProjectMaterialIcons.kt"

function Find-SourceJar {
    param(
        [string]$ArtifactName
    )

    $jar = Get-ChildItem "$env:USERPROFILE\.gradle\caches\modules-2\files-2.1\androidx.compose.material\$ArtifactName-android" `
        -Recurse -Filter "*sources.jar" -ErrorAction SilentlyContinue |
        Where-Object { $_.Name -notlike "*samples*" } |
        Sort-Object FullName -Descending |
        Select-Object -First 1

    if (-not $jar) {
        throw "Could not find sources jar for $ArtifactName-android in the local Gradle cache."
    }

    return $jar.FullName
}

function Read-ZipEntryText {
    param(
        [System.IO.Compression.ZipArchive]$Zip,
        [string]$EntryName
    )

    $entry = $Zip.GetEntry($EntryName)
    if (-not $entry) {
        throw "Missing zip entry: $EntryName"
    }

    $reader = [System.IO.StreamReader]::new($entry.Open())
    try {
        return $reader.ReadToEnd()
    } finally {
        $reader.Dispose()
    }
}

function Get-UsedIcons {
    param(
        [string]$Root,
        [string]$StylePattern
    )

    $pattern = "Icons\.$StylePattern\.([A-Za-z0-9]+)"
    $matches = Get-ChildItem $Root -Recurse -Filter *.kt |
        Select-String -Pattern $pattern -AllMatches

    return $matches.Matches |
        ForEach-Object { $_.Groups[1].Value } |
        Sort-Object -Unique
}

function Get-CoreIcons {
    param(
        [System.IO.Compression.ZipArchive]$Zip,
        [string]$SourceFolder
    )

    return $Zip.Entries |
        Where-Object { $_.FullName -like "commonMain/androidx/compose/material/icons/$SourceFolder/*.kt" } |
        ForEach-Object {
            if ($_.FullName -match "/([A-Za-z0-9]+)\.kt$") {
                $matches[1]
            }
        } |
        Sort-Object -Unique
}

function Build-SubsetSource {
    param(
        [System.IO.Compression.ZipArchive]$Zip,
        [string[]]$IconNames,
        [string]$PackageName,
        [string]$SourceFolder,
        [string]$ReceiverName
    )

    $imports = [System.Collections.Generic.HashSet[string]]::new()
    $bodyParts = [System.Collections.Generic.List[string]]::new()

    foreach ($iconName in $IconNames) {
        $entryName = "commonMain/androidx/compose/material/icons/$SourceFolder/$iconName.kt"
        $source = Read-ZipEntryText -Zip $Zip -EntryName $entryName

        foreach ($importLine in ($source -split "`r?`n" | Where-Object { $_ -like "import *" })) {
            [void]$imports.Add($importLine)
        }

        $receiverPattern = [regex]::Escape($ReceiverName)
        $iconPattern = [regex]::Escape($iconName)
        $pattern = "(?ms)^public val Icons\.${receiverPattern}\.${iconPattern}: ImageVector.*?^private var _[A-Za-z0-9]+: ImageVector\? = null\s*$"
        $body = [regex]::Match($source, $pattern)
        if (-not $body.Success) {
            throw "Could not extract icon body for $PackageName.$iconName"
        }

        [void]$bodyParts.Add($body.Value.Trim())
    }

    $sortedImports = @($imports) | Sort-Object
    $header = @(
        "/*"
        " * Local subset of Compose Material icons generated from"
        " * androidx.compose.material:material-icons-extended sources."
        " */"
        ""
        "package $PackageName"
        ""
    )

    return ($header + $sortedImports + "" + "// Generated by tools/generate-material-icon-subset.ps1." + "" + ($bodyParts -join "`r`n`r`n") + "") -join "`r`n"
}

Add-Type -AssemblyName System.IO.Compression.FileSystem
$coreJarPath = Find-SourceJar -ArtifactName "material-icons-core"
$extendedJarPath = Find-SourceJar -ArtifactName "material-icons-extended"
$coreZip = [System.IO.Compression.ZipFile]::OpenRead($coreJarPath)
$extendedZip = [System.IO.Compression.ZipFile]::OpenRead($extendedJarPath)

try {
    $usedFilled = Get-UsedIcons -Root $appSources -StylePattern "Default"
    $usedAutoMirrored = Get-UsedIcons -Root $appSources -StylePattern "AutoMirrored\.Filled"

    $coreFilled = Get-CoreIcons -Zip $coreZip -SourceFolder "filled"
    $coreAutoMirrored = Get-CoreIcons -Zip $coreZip -SourceFolder "automirrored/filled"

    $missingFilled = $usedFilled | Where-Object { $_ -notin $coreFilled }
    $missingAutoMirrored = $usedAutoMirrored | Where-Object { $_ -notin $coreAutoMirrored }

    $filledSource = Build-SubsetSource `
        -Zip $extendedZip `
        -IconNames $missingFilled `
        -PackageName "androidx.compose.material.icons.filled" `
        -SourceFolder "filled" `
        -ReceiverName "Filled"
    $autoMirroredSource = Build-SubsetSource `
        -Zip $extendedZip `
        -IconNames $missingAutoMirrored `
        -PackageName "androidx.compose.material.icons.automirrored.filled" `
        -SourceFolder "automirrored/filled" `
        -ReceiverName "AutoMirrored.Filled"

    New-Item -ItemType Directory -Force -Path (Split-Path -Parent $filledOutput) | Out-Null
    New-Item -ItemType Directory -Force -Path (Split-Path -Parent $autoMirroredOutput) | Out-Null

    Set-Content -Path $filledOutput -Value $filledSource -Encoding UTF8
    Set-Content -Path $autoMirroredOutput -Value $autoMirroredSource -Encoding UTF8
} finally {
    $coreZip.Dispose()
    $extendedZip.Dispose()
}
